### ISSUE TITLE
GIS.lab client: request IP address directly from GIS.lab server

### ISSUE THREAD

**Issue by imincik** [imincik/gis-lab#333]
There is a problem with requesting client IP address if other DHCP server exists in LAN. 

'udhcpc' client used on GIS.lab client is sending broadcast request to network and will process only first response it will receive. If this response is not from GIS.lab server, but from some another server, it will refuse it and will try again. This can cause many loops until response from GIS.lab server will be a first one.

According RFC 2131, it is possible to send also unicast server to particular server.

RFC 2131
4.4.4 Use of broadcast and unicast

The DHCP client broadcasts DHCPDISCOVER, DHCPREQUEST and DHCPINFORM
messages, unless the client knows the address of a DHCP server.
The client unicasts DHCPRELEASE messages to the server. Because
the client is declining the use of the IP address supplied by the server,
the client broadcasts DHCPDECLINE messages.

When the DHCP client knows the address of a DHCP server, in either
INIT or REBOOTING state, the client may use that address
in the DHCPDISCOVER or DHCPREQUEST rather than the IP broadcast address.
The client may also use unicast to send DHCPINFORM messages
to a known DHCP server. If the client receives no response to DHCP
messages sent to the IP address of a known DHCP server, the DHCP
client reverts to using the IP broadcast address.

In 'busybox-1.18.5/networking/udhcp/dhcpc.c' 'raw_bcast_from_client_config_ifindex' function is used to send broadcast requests. It is possible to send unicast request using function 'udhcp_send_kernel_packet'. 

We can try to add possiblity (commandline option) to choose between broadcast and unicast to DHCPDISCOVER and DHCPREQUEST requests .

See:
* http://en.wikipedia.org/wiki/Dynamic_Host_Configuration_Protocol#mediaviewer/File:DHCP_session_en.svg

Downloading source code:
$ apt-get source busybox-static

Example running udhcpc:
$ sudo busybox udhcpc -h
$ sudo busybox udhcpc

Building Debian package
$ dpkg-buildpackage -us -uc

**Comment by peter-kolenic** [comment]
please let me know, if what You want is the behaviour of this:
(diff to gis-lab server: apt-get source busybox)
https://gist.github.com/peter-kolenic/a7ceef32fab2a638712e
If, i will add options to udhcpc.

**Comment by imincik** [comment]
@peter-kolenic,  I think, it is also required to add unicast to 'REQUEST' request (See DHCP schema above). Would you please check it ?

**Comment by imincik** [comment]
This is what I see in DHCP serve logs apter applying patch:

16:52:01.591057 IP (tos 0x0, ttl 64, id 0, offset 0, flags [none], proto UDP (17), length 322)
    0.0.0.0.bootpc > 255.255.255.255.bootps: [udp sum ok] BOOTP/DHCP, Request from 00:1d:92:26:f1:e3 (oui Unknown), length 294, xid 0x6d3e3c6b, Flags [none] (0x0000)
          Client-Ethernet-Address 00:1d:92:26:f1:e3 (oui Unknown)
          Vendor-rfc1048 Extensions
            Magic Cookie 0x63825363
            DHCP-Message Option 53, length 1: Discover
            MSZ Option 57, length 2: 576
            Parameter-Request Option 55, length 7: 
              Subnet-Mask, Default-Gateway, Domain-Name-Server, Hostname
              Domain-Name, BR, NTP
            Vendor-Class Option 60, length 12: "udhcp 1.18.5"
            YD Option 40, length 21: "gislab_vagrant-client"


It seems that client is not sending unicats request.

**Comment by peter-kolenic** [comment]
@imincik:
ad udhcp_send_kernel_packet: it is unusable in this case, interfaces dont's have IP yes -> kernel has no idea which interface to use

ad unicast REQUEST: let's check behaviour of unicast DISCOVERY first, whether Your DHCP server responds with OFFER or not. REQUEST is reply to OFFER, i expect other DHCP servers on the net to silently ignore it (as it is, from their point of view, indistinguishable to scenario of broadcast DISCOVERY UDP packet never reaching them; UDP does not guarantee delivery).

What You see in tcpdump is what i saw before the patch. Just to be sure that what is run is patched, i have updated the gist with debug output and rebuilded the package again:
apt-get source busybox
patch busybox-1.18.5/networking/udhcp/dhcpc.c
dpkg-buildpackage -rfakeroot -uc -b

my packet looks like:
18:15:42.422108 IP (tos 0x0, ttl 64, id 0, offset 0, flags [none], proto UDP (17), length 308)
    0.0.0.0.68 > 192.168.60.1.67: BOOTP/DHCP, Request from 08:00:27:b9:ea:02, length 280, xid 0xcf62a68, Flags [none]
	  Client-Ethernet-Address 08:00:27:b9:ea:02
	  Vendor-rfc1048 Extensions
	    Magic Cookie 0x63825363
	    DHCP-Message Option 53, length 1: Discover
	    Client-ID Option 61, length 7: ether 08:00:27:b9:ea:02
	    MSZ Option 57, length 2: 576
	    Parameter-Request Option 55, length 7: 
	      Subnet-Mask, Default-Gateway, Domain-Name-Server, Hostname
	      Domain-Name, BR, NTP
	    Vendor-Class Option 60, length 12: "udhcp 1.18.5"

my binary busybox-1.18.5/debian/build/build_static/busybox is here:
https://www.dropbox.com/s/lxdrhkm07dax31b/busybox?dl=0

this should be in output
udhcpc (v1.18.5) started
Sending discover...
unicast packet to addr: 13ca8c0(hex)

If You let me know the IP You need in Your testing environment, i can build the binary for You.

**Comment by peter-kolenic** [comment]
OK, then please try updated gist, and let me know if it works in Your environment. It should ignore all but one  DHCP server.

**Comment by imincik** [comment]
@peter-kolenic, I confirm that your new patch is working !

Please add new option '-x' ADDRESS, --filter=ADDRESS accept responses only from server with IP address ADDRESS

**Comment by peter-kolenic** [comment]
@imincik: -I, --server-filter, please check updated gist:
https://gist.github.com/peter-kolenic/a7ceef32fab2a638712e

**Comment by peter-kolenic** [comment]
@imincik 
https://gist.github.com/peter-kolenic/2e20ce41f0d6e6f6eeb2
clearer patch

**Comment by imincik** [comment]
@peter-kolenic, I confirm, that your latest patch is working. Thank you very much.

Now, I am going to release patched busybox version for GIS.lab in ppa:imincik/general
