### ISSUE TITLE
GIS.lab Web plugin: publishing of new SpatiaLite layers is not working until project is reopen

### ISSUE THREAD

**Issue by imincik** [imincik/gis-lab#344]
Publishing of new SpatiaLite layers is not working until project is reopen.

Steps to replicate problem:
* create new SpatiaLite layer in DB Manager
* draw some features to new layer
* publish map in GIS.lab Web - it will not work
* save QGIS project and close it
* open QGIS project and publish map in GIS.lab Web - it will work now

**Comment by marcel-dancak** [comment]
Related bug report in QGIS http://hub.qgis.org/issues/8923

**Comment by marcel-dancak** [comment]
Even more related bug report https://hub.qgis.org/issues/8908
