### ISSUE TITLE
QGIS attributes added to spatialite layer will disappear after re-opening project

### ISSUE THREAD

**Issue by marcel-dancak** [imincik/gis-lab#349]
Spatialite provider will not update layer statistics after adding a new attributes to spatialite layer. It's already fixed in qgis master branch.

More details in bug report http://hub.qgis.org/issues/8923

**Comment by marcel-dancak** [comment]
Patch for QGIS 2.2 version: https://github.com/marcel-dancak/QGIS/commit/ea115d8eaaf5b41f21345d6e6d396658548b7e9f

It's possible that there can be problem in master branch in loading layer's fields (data types). We should check how spatialite provider fetch data types when there is no data values stored in features fields with INTEGER or DOUBLE data types (whether it will be treated as TEXT).

**Comment by imincik** [comment]
Uploaded to ppa:imincik/gis-dev

**Comment by imincik** [comment]
Uploaded to ppa:imincik/gis.
