### ISSUE TITLE
Manual detection: Could not store "ip" (empty value)

### ISSUE THREAD

**Issue by landam** [imincik/gis-lab#362]
When booting GIS.lab unit in "Manual detection" mode and setting network to empty value, the detection fails with

```
Could not store "ip": Invalid argument
```

The interface doesn't allow to correct the network value. It's only suggesting:

F1 to retry boot, which tries to boot again, but obviously fails
F2 ("setup utility") ends with a black screen with white mouse cursor in the center of the screen, than only "hard restart" helps
F5 ("to run onboard diagnostics") does surprisingly reboot

**Comment by imincik** [comment]
Thanks for reporting. To install updated boot manager use following steps:

$ gunzip -c ./gislab-client-loader.iso.gz > ./gislab-client-loader.iso

$ sudo dd if=./gislab-client-loader.iso of=/dev/sd[x]
