### ISSUE TITLE
Add Amazon AWS support

### ISSUE THREAD

**Issue by imincik** [imincik/gis-lab#367]
Since moving to Ansible, we are missing AWS support. We need to implement special provider init playbook (similar to GIS.lab Unit). Than run standard GIS.lab installation.

Separate images builds to separate roles (client-desktop-image-pxe, client-desktop-image-aws) and add new configuration variable GISLAB_PROVIDER which will activate list of providers (lan, aws).

* init playbook (providers/amazon/amazon.yml): security zones, mount first ephemeral disk to /storage
* standard installation
* post-init playbook: register worker image on S3 and start desired number of workers

* group_vars/all: add 'PROVIDER' section after 'ADMINISTRATOR DETAILS' with 'GISLAB_PROVIDER' (default 'lan') and continue with GISLAB_AWS_ variables

**Comment by mpastor** [comment]
Ephemeral disk cannot be mounted in a initial playbook because instance is not running.

**Comment by mpastor** [comment]
The only available user in new instance is root. Should be this account used for installation?

**Comment by imincik** [comment]
Implemented in 455fcc7e8157f7c1b37cfa9cbe915ca58591fe49
