### ISSUE TITLE
GIS.lab's DHCP server is breaking LAN even if unknown machine policy is set to 'deny'

### ISSUE THREAD

**Issue by imincik** [imincik/gis-lab#379]
GIS.lab's DHCP server is breaking LAN even if unknown machine policy is set to 'deny', because it is sending NAK (wrong network) responses when client computer is handshaking with other server. 

It seems that blocking DHCP traffic by ebtables is th only one solution.

See:
* http://balajitheone.blogspot.sk/2011/04/dhcp-server-was-getting-continuous.html
* http://ebtables.netfilter.org/examples/basic.html#ex_nobridge

**Comment by mpastor** [comment]
##### Simple fix for virtualbox:

 # install packages
```apt-get install bridge-utils ebtables```

 # drop GIS.lab server IP address
```ip addr del $GISLAB_NETWORK.5/24 dev eth1```

 # create bridge
```brctl addbr br0```

 # add eth1 to bridge
```brctl addif br0 eth1```

 # bring up bridge
```ip link set br0 up```

 # add GIS.lab server IP address to bridge
```ip addr add $GISLAB_NETWORK.5/24 dev br0```

 # change DHCP server configuration
```
sed -i 's/eth1/br0/' /etc/default/isc-dhcp-server
service isc-dhcp-server restart
```

 # create new chain
```ebtables -N dhcp```

 # set default policy for chain 'dhcp' - this will drop all DHCP request from unknow machines
```ebtables -P dhcp DROP```

 # redirect all DHCP requests to chain 'dhcp'
```ebtables -t filter -I INPUT --protocol IPv4 --ip-protocol udp --ip-source-port 68 --ip-destination-port 67 -j dhcp```

 # allow DHCP request from GIS.lab client (MAC address) in chain 'dhcp' (repeat for each client)
```ebtables -t filter -A dhcp -s 00:11:22:33:44:55 -j ACCEPT```

 # deny client
```ebtables -t filter -D dhcp -s 00:11:22:33:44:55 -j ACCEPT```

###### Edit /etc/network/interfaces to make changes permanent:

```
iface eth1 inet manual

iface br0 inet static
        bridge_ports eth1
        address $GISLAB_NETWORK.5
        netmask 255.255.255.0
        broadcast $GISLAB_NETWORK.255
```

**Comment by mpastor** [comment]
##### Simple fix for gislab-unit:

 # install packages
```apt-get install bridge-utils ebtables```

 # edit /etc/network/interfaces
```
iface eth0 inet manual

auto br0
iface br0 inet dhcp
        bridge_ports eth0
```

 # modify /etc/network/if-up.d/gislab
```sed -i 's/eth0/br0/' /etc/network/if-up.d/gislab```

  # modify DHCP server configuration
```
sed -i 's/eth0/br0/' /etc/default/isc-dhcp-server
service isc-dhcp-server restart
```

Reboot  GIS.lab server and apply ebtables rules.
