### ISSUE TITLE
GIS.lab client - add more information to desktop session lock file

### ISSUE THREAD

**Issue by imincik** [imincik/gis-lab#398]
Add more information to desktop session lock file ($HOME/.gislab/session.lock) for example IP address, hostname or MAC address. Use this information also for "gislab-cluster query client-session-active" cluster query.

Also, it would be fine to print better message when user is trying to launch concurrent session.

**Comment by hroncok** [comment]
Why is concurrent session forbidden in the first place?

**Comment by imincik** [comment]
Hi @hroncok, I am afraid, that allowing concurrent session would break applications which are storing some runtime configuration in in user's home directory. For example, I don't know what would happen if user will change some XFCE configuration in one session while running other session. Also, I remember that Firefox couldn't handle concurrent run at all.

But I would welcome any advice.

**Comment by hroncok** [comment]
I'm quite sure Xfce can handle this. I use concurrent sessions regularly in
Xfce.

**Comment by imincik** [comment]
I see you are XFCE user. I am still not sure about Firefox or LibreOffice. Do you think it is worth to allow concurrency even some problems can occur ?

I see one more possible problem, as we use GIS.lab for education, we use some non personalized user names like user1, user2, user3 for our classes. If we would allow concurrent sessions, it can easily happen that two students can login with the same user name. They will overwrite data to each other and so on.

**Comment by hroncok** [comment]
Is LibreOffice somehow crucial for gis-lab?

I don't know about Firefox, sorry, you'll have to try that.

If you really need this, wouldn't it be better idea to actually check, if the other session is running?
