### ISSUE TITLE
GIS.lab client - Use NscD for caching LDAP requests 

### ISSUE THREAD

**Issue by imincik** [imincik/gis-lab#400]
Use NscD for caching LDAP requests:

Example nslcd config:

```
# /etc/nslcd.conf
# nslcd configuration file. See nslcd.conf(5)
# for details.

# The user and group nslcd should run as.
uid nslcd
gid nslcd

# The location at which the LDAP server(s) should be reachable.
uri ldaps://ldap.tolabaki.gr:636/

# The search base that will be used for all queries.
base dc=tolabaki,dc=gr

# The DN to bind with for normal lookups.
binddn cn=agent,dc=tolabaki,dc=gr
bindpw <secret>

# SSL options
tls_reqcert demand
tls_cacertfile /etc/ssl/certs/cacert-root.pem
```

See:
* http://wiki.tolabaki.gr/w/Authentication

**Comment by mpastor** [comment]
Local LDAP caching daemon is 'nscd' not 'nslcd'.

http://www.techrepublic.com/blog/linux-and-open-source/authentication-caching-with-nscd/

**Comment by mpastor** [comment]
nscd breaks sudo on clients:
```
$ sudo su -
sudo: ldap_start_tls_s(): Connect error
[sudo] password for gislab: 
gislab is not in the sudoers file.  This incident will be reported.
```

**Comment by mpastor** [comment]
because of problems with sudo and a lot of negative experiences with nscd (hanging, crashing), we decided to not use nscd.
the number of queries to LDAP server was reduced by changing conky configuration.

**Comment by mpastor** [comment]
Adding
```
TLS_CHECKPEER no
```
to /etc/ldap/ldap.conf solve the problem with sudo. this fix the another problem (with the same symptons) with sudo:
```
root@c50:~# sudo su - gislab
sudo: ldap_start_tls_s(): Connect error
gislab@c50.GIS.lab(gislab_vagrant):~$
```

**Comment by imincik** [comment]
So should we implement 'TLS_CHECKPEER no' ?

**Comment by mpastor** [comment]
definitely yes.

**Comment by imincik** [comment]
So, can you apply it to master branch ?

**Comment by mpastor** [comment]
Applied to master. Closing.
