### ISSUE TITLE
GIS.lab client - Invalid response packet from host from Avahi daemon

### ISSUE THREAD

**Issue by imincik** [imincik/gis-lab#411]
This bug report is written mostly for reference.
Avahi daemon running on client machines is flooding syslog with 'Invalid response packet from host' messages. Here are corresponding bug records:
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=556461
* https://bugs.launchpad.net/ubuntu/+source/avahi/+bug/1342400

**Comment by mpastor** [comment]
in fact avahi is unnecessary and can be safely removed.

**Comment by imincik** [comment]
I was considering to remove Avahi, but don't we need it for printers ?
