### ISSUE TITLE
Could not read from the boot medium! System halted.

### ISSUE THREAD

**Issue by Comiii** [imincik/gis-lab#419]
Hi. I try to setup GIS.lab. I am using Windows 2008 Server. I install virtual box and  vagrant. After that i setup Virtual box like it with instructions from documentation(https://github.com/imincik/gis-lab/wiki/Virtual-Client). The problem is when I try to start  gis.lab I am getting error:
No more network device.
Could not read from the boot medium! System halted.
![vbox](https://cloud.githubusercontent.com/assets/6542322/8888245/e46c65f8-32a5-11e5-96f6-26891baf0154.jpg)

**Comment by imincik** [comment]
Hi @Comiii, where is your GIS.lab Server installed ?
Have you followed Quick Start instructions ? [1]. Please notice that installation of GIS.lab Server using Vagrant is not supported on Windows due some Ansible limitations. Client interfaces (this is what you are trying to run) are running fine on Win, Linux or Mac.

1 - https://github.com/imincik/gis-lab/wiki/Quick-Start

**Comment by imincik** [comment]
One more notice, your question is more suitable for GIS.lab MailingList [2]. It is more support question than a bug.

2 - http://lists.osgeo.org/cgi-bin/mailman/listinfo/gis.lab

**Comment by imincik** [comment]
Closing this issue since it is more support question suitable to mailinglist.
