### ISSUE TITLE
GIS.lab Unit ISO creation improvements

### ISSUE THREAD

**Issue by imincik** [imincik/gis-lab#422]
* set Apt Proxy configuration at the beginning of installation process (remove it from ./gislab-unit-iso.sh)
* change ISO image name from 'Ubuntu ...' to GIS.lab $ISO_ID (stored in ./.disk/info and ./README.diskdefines)

**Comment by mpastor** [comment]
Implemented in 1fe350c30032c6c040b81be814650d3691bc454a, d31aa49836c986a789083d8b4adae3712030793c and 1fde3170f9ec69d2ea50bdad5230850590cd85cb.
