### ISSUE TITLE
GIS.lab Desktop - add support to renew DHCP lease from server

### ISSUE THREAD

**Issue by imincik** [imincik/gis-lab#432]
Currently, DHCP lease from server is not renewed. We need to copy lease from ramdisk to client filesystem a connect it correctly to dhcp client to enable DHCP renew request.

In current state, we have running useless "udhcpc -n -C -s /tmp/dhcp-script.sh -i eth0 -I 192.168.15.5 -x nisdomain gislab_vagrant" process on client. " /tmp/dhcp-script.sh" exists only in ramdisk.

**Comment by mpastor** [comment]
I set lease time to 2 minutes. client has successfully renewed ip address (without dhcp script and without lease file created in ramdisk) every 2 minutes. i think that udhcpc is running in RAM without any additional requirements. I have also successfully renewed ip address manualy (kill -USR1 [PID])

**Comment by imincik** [comment]
Closing, it works !
