### ISSUE TITLE
GIS.lab - problem with installation (GRASS locations)

### ISSUE THREAD

**Issue by lfurtkevicova** [imincik/gis-lab#436]
Installation failed with this error:

![gislab_install_error](https://cloud.githubusercontent.com/assets/13394357/10244983/b115fc84-6903-11e5-9356-2ccb7493da42.png)

**Comment by imincik** [comment]
@lfurtkevicova, thank for reporting.
It works on my machine. Do you use the latest GIS.lab version from git ?
Also, can you please paste here the output of following commands?

$ vagrant --version
$ ansible --version
$ df -h

**Comment by lfurtkevicova** [comment]
Versions: 
VAGRANT: 1.7.4
ANSIBLE: 1.5.4

printout of df -h:
Súborový systém  Veľk  Použ  Dost Pou% Pripojený na
/dev/sdb9        8,4G  6,6G  1,4G  84% /
none             4,0K     0  4,0K   0% /sys/fs/cgroup
udev             1,9G  4,0K  1,9G   1% /dev
tmpfs            382M  1,4M  380M   1% /run
none             5,0M     0  5,0M   0% /run/lock
none             1,9G   60M  1,9G   4% /run/shm
none             100M   60K  100M   1% /run/user
/dev/sdb11       145G  4,5G  133G   4% /home
/dev/sdb2        256M   32M  225M  13% /boot/efi

**Comment by imincik** [comment]
@lfurtkevicova, you are running very old Ansible version. I guess this is the problem.

Please try following commands to upgrade Ansible:
```
$ sudo apt-get install software-properties-common
$ sudo apt-add-repository ppa:ansible/ansible
$ sudo apt-get update

$ sudo apt-get install ansible
```

Then try to reinstall GIS.lab again with latest version in git (some installer bugs where fixed few minutes ago):
```
$ git pull
$ vagrant destroy
$ vagrant up
```

**Comment by lfurtkevicova** [comment]
After ansible installation:

``fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).``

**Comment by imincik** [comment]
@lfurtkevicova , you must run 'git pull' command in GIS.lab source code directory which in your case is '~/gis-lab'

**Comment by lfurtkevicova** [comment]
@imincik thanks a lot ... :+1: 

```
TASK: [installation-done | Installation of GIS.lab is done] ******************* 
changed: [gislab_vagrant]

PLAY RECAP ******************************************************************** 
gislab_vagrant             : ok=453  changed=397  unreachable=0    failed=
```
