### ISSUE TITLE
Possibility to arrange windows side by side

### ISSUE THREAD

**Issue by lfurtkevicova** [imincik/gis-lab#441]
Add possibility to snap an active window to the side of the desktop (after dragging the title bar of a window to the left or right side of the screen)

**Comment by imincik** [comment]
Hi @lfurtkevicova, widows snapping and tiling is a feature of window manager which is used as is in GIS.lab. Once this feature will be developed by upstream, it will be available also in GIS.lab.

I am closing this issue as wonfix.
