### ISSUE TITLE
add support for user groups

### ISSUE THREAD

**Issue by landam** [imincik/gis-lab#457]
Currently GIS.lab users are by default members of `gislabusers` and `gislabadmins` (only superusers) group. It would be useful to manage also other admin-defined groups. That would require to add new admin commands like:

 * `gislab-addgroup`
 * `gislab-delgroup`

And a new parameter for `gislab-adduser` to define membership for newly created users (eg. `-r`):

```
-r List of admin-defined groups

sudo gislab-addgroup group1
sudo gislab-adduser -g User -l GIS.lab -m lab1@gis.lab -p lab -r group1 lab1
```

Then the user `lab1` will be member of `gislabusers` and `group1`.

Or to modify usage of already used `-s` parameter (which defines superusers)

```
sudo gislab-adduser -g User -l GIS.lab -m lab1@gis.lab -p lab -s gislabadmins lab1

sudo gislab-addgroup group1
sudo gislab-adduser -g User -l GIS.lab -m lab1@gis.lab -p lab -s gislabadmins,group1 lab2
```

Then `lab1` will be member of `gislabusers` and `gislabadmins`, `lab2` --- `gislabusers`, `gislabadmins` and `group1`.

**Comment by landam** [comment]
It would be also useful to introduce new admin commands:

 * `gislab-listusers`
 * `gislab-listgroups`

**Comment by imincik** [comment]
@mpastor , please add tests for gislab-addgroup, gislab-delgroup, gislab-listusers, gislab-listgroups

**Comment by imincik** [comment]
Implemented in multiple recent commits.
