### ISSUE TITLE
Django filter url endpoint

### ISSUE THREAD

**Issue by jachym** [imincik/gis-lab#462]
url: /filter?PROJECT=PROJECT_NAME

POST filter configuration

```javascript
{ 
     layername: {
        attribute1: {
              value: "value",
              operator: "="
     },
     attribute2: {
     ....
     }
}

```

Uses OWSLib for WFS GetFeatures request and FES generated query

Uses paging

returns JSON with data

**Comment by imincik** [comment]
Hi @jachym, if this issue is still valid, please move it to https://github.com/imincik/gislab-web-mobile/issues

**Comment by jachym** [comment]
ticket moved to https://github.com/imincik/gislab-web-mobile/issues/1
